### ISSUE TITLE
Support for Crystal 0.35.1

### ISSUE THREAD

**Issue by confact** [maiha/pretty.cr#3]
Logger is deprecated and is now called Log.

Could you update this?

**Comment by maiha** [comment]
One of this library's goals is to provide backward compatibility for crystal, which frequently makes incompatible modifications.

In this case of Log support, it's going to take some time because it will require to support for both, rather than a simple replacement of Logger to Log.

**Comment by confact** [comment]
@maiha would love it to work or some hotfix I can do in a fork or something, I am using clickhouse.cr on my lucky app and gets deprecated warnings all the time.

**Comment by maiha** [comment]
@confact 
Backwards compatibility is important, but it certainly doesn't feel good if it doesn't work with the latest version or if you keep getting massive warnings.

I haven't decided whether I should keep the two `Log` classes together or cut them out to different branches, but I'll try to resolve this issue first, so please wait a week or so.

**Comment by confact** [comment]
@maiha how is it going with this? Anything I can help with to push this forward? I would like this to be fixed :)

**Comment by maiha** [comment]
@confact 
Sorry. I haven't decided how I'm going to handle the two classes yet.

However, I've found that deprecated warnings can be suppressed by `--exclude-warnings <PATH>`.
I hope this helps your case. Could you try something like this?

```console
$ crystal run --exclude-warnings lib "YOUR_APP.cr"
$ crystal run --exclude-warnings lib --exclude-warnings /usr/share/crystal/src/logger.cr "YOUR_APP.cr"
```

FYI: I updated `clickhouse.cr` to work with crystal-0.35.1.

**Comment by maiha** [comment]
Dropped logger dependency when it is not loaded in v1.0.0.
